import os
import sys
import argparse
import json

if sys.stdout.encoding != 'utf-8':
    sys.stdout.reconfigure(encoding='utf-8')

sys.path.append(os.path.join(os.path.dirname(__file__), "connectors"))
try:
    import wp_rest_connector
except ImportError as e:
    print(f"Error loading connector: {e}")
    sys.exit(1)

def run_phase1_context_assembly(keyword: str) -> dict:
    """
    Phase 1: Profile & Context Assembly
    Simulates scraping top 3 competitors and finding information gaps.
    """
    print(f"\n[Phase 1] Assembling Context for keyword: '{keyword}'")
    print(" 🔍 Simulating SERP Top 3 scrape...")
    print(" 🧠 Running Information Gap Analysis...")
    
    # In a real scenario, this would use serp_competitor and an LLM call
    context = {
        "keyword": keyword,
        "search_intent": "Informational",
        "missing_angles": [
            "Real-world case studies",
            "Cost comparison tables",
            "Expert quotes"
        ]
    }
    return context

def run_phase2_generation(context: dict) -> str:
    """
    Phase 2: LLM Generation
    Uses the context to generate E-E-A-T compliant markdown.
    """
    print(f"\n[Phase 2] Generating Content via LLM...")
    kw = context['keyword']
    angles = ", ".join(context['missing_angles'])
    
    print(f" ✍️ Enforcing E-E-A-T standards and Information Gains: {angles}")
    
    # Dummy LLM generation
    content_html = f"""
    <!-- wp:heading -->
    <h2 class="wp-block-heading">Introduction to {kw}</h2>
    <!-- /wp:heading -->
    <!-- wp:paragraph -->
    <p>This is an automated article generated by SEOSONA OS Auto-Blogger V2.</p>
    <p>Target Keyword: <strong>{kw}</strong></p>
    <!-- /wp:paragraph -->
    <!-- wp:heading {{"level":3}} -->
    <h3 class="wp-block-heading">Information Gains Added:</h3>
    <!-- /wp:heading -->
    <!-- wp:list -->
    <ul>
        <li>{context['missing_angles'][0]}</li>
        <li>{context['missing_angles'][1]}</li>
        <li>{context['missing_angles'][2]}</li>
    </ul>
    <!-- /wp:list -->
    """
    return content_html

def run_phase3_post_processing(wp_url: str, title: str, content_html: str, dry_run: bool):
    """
    Phase 3: Post-Processing & Push to WP
    Injects Schema and pushes to WP REST API.
    """
    print(f"\n[Phase 3] Post-Processing & WP Integration...")
    print(" ⚙️ Generating JSON-LD Schema...")
    
    schema = {
        "@context": "https://schema.org",
        "@type": "Article",
        "headline": title
    }
    
    # Append schema to content
    final_content = content_html + f"\n<script type='application/ld+json'>{json.dumps(schema)}</script>"
    
    if dry_run:
        print(" 🚨 DRY RUN MODE: Skipping actual POST to WordPress.")
        res = wp_rest_connector.run(wp_url, title, final_content, "draft")
    else:
        print(" 🚀 Pushing to WordPress API...")
        res = wp_rest_connector.run(wp_url, title, final_content, "draft")
        
    # res is a FixLoopResult, we can just print it
    print(f" ✅ Result: {getattr(res, 'data', res)}")


def main():
    parser = argparse.ArgumentParser(description="SEOSONA OS Auto-Blogger V2")
    parser.add_argument("--keyword", required=True, help="Target keyword")
    parser.add_argument("--wp-url", required=True, help="WordPress URL")
    parser.add_argument("--dry-run", action="store_true", help="Do not actually post to WP")
    
    args = parser.parse_args()
    
    print("="*50)
    print(" SEOSONA OS Auto-Blogger V2 Pipeline")
    print("="*50)
    
    # Run the pipeline
    context = run_phase1_context_assembly(args.keyword)
    content = run_phase2_generation(context)
    title = f"The Ultimate Guide to {args.keyword} (2026)"
    
    run_phase3_post_processing(args.wp_url, title, content, args.dry_run)

if __name__ == "__main__":
    main()
