import os
import time
import json
import glob
from pathlib import Path

# Thư mục gốc chứa logs và INBOX
SEOSONA_DIR = Path(__file__).resolve().parents[3]
AGENT_INBOX = (SEOSONA_DIR / ".agents" / "INBOX")
BRAIN_LOGS_DIR = Path(os.path.expanduser("~/.gemini/antigravity-ide/brain"))

class OAAcademy:
    """
    OA Academy (Self-Evolution Engine).
    Mission: Listens for exceptions, 'command not found' errors 
    from Agent logs. If repeated errors occur, it automatically generates a template
    requesting a new Skill and sends it to the INBOX for `skill-creator-ultra`.
    """
    def __init__(self):
        self.error_patterns = [
            "command not found",
            "ImportError",
            "missing dependency",
            "ModuleNotFoundError",
            "invalid tool call"
        ]
        self.analyzed_files = set()

    def scan_for_errors(self):
        print("[OA Academy] Scanning system for knowledge gaps...")
        # Get all task log files
        log_files = glob.glob(str(BRAIN_LOGS_DIR / "**/.system_generated/tasks/*.log"), recursive=True)
        
        detected_gaps = []
        for log_file in log_files:
            if log_file in self.analyzed_files:
                continue
                
            try:
                with open(log_file, 'r', encoding='utf-8') as f:
                    content = f.read()
                    
                for pattern in self.error_patterns:
                    if pattern in content:
                        detected_gaps.append((log_file, pattern))
                        break
                        
                self.analyzed_files.add(log_file)
            except Exception as e:
                pass
                
        return detected_gaps

    def draft_skill_request(self, gap):
        log_file, pattern = gap
        print(f"[OA Academy] Detected knowledge gap: '{pattern}' in {os.path.basename(log_file)}.")
        
        # Generate blueprint requesting a new skill
        blueprint_name = f"skill_request_{int(time.time())}.md"
        blueprint_path = AGENT_INBOX / blueprint_name
        
        blueprint_content = f"""# Autonomous Skill Creation Request (Generated by OA Academy)

## Context
System detected recurring error: `{pattern}`
Log source: `{log_file}`

## Instructions for skill-creator-ultra
Please analyze the error above and create a Python or PowerShell script/skill to permanently fix it. 
Remember to package it according to the 3-Tier Protocol and save it to `.agents/skills/_TIER_2_LAZY_LOAD/`.
"""
        AGENT_INBOX.mkdir(parents=True, exist_ok=True)
        with open(blueprint_path, 'w', encoding='utf-8') as f:
            f.write(blueprint_content)
            
        print(f"-> Sent new skill request blueprint to INBOX: {blueprint_path}")

    def run(self):
        print("Starting OA Academy (Self-Evolution Engine)...")
        while True:
            gaps = self.scan_for_errors()
            for gap in gaps:
                self.draft_skill_request(gap)
                
            time.sleep(60) # Run in background every 60s

if __name__ == "__main__":
    academy = OAAcademy()
    academy.run()
